### PR TITLE
Expose port 80 for the christmas-community service

### PR DESCRIPTION
**Pull request by coalio**
If the app is ran with docker-compose, the express server (port 80) should be open as well

### CODE REVIEW

**Comment by Wingysam** [comment]
Christmas Community by default listens on 3000, not 80. Does forwarding 80 have some benefit that I'm not understanding?

**Comment by coalio** [comment]
Yes, the express server starts at port 80 instead of 3000 if you build the service using the Dockerfile, as expressed [in this line](https://github.com/Wingysam/Christmas-Community/blob/fe6bf0f474f3fbbd8aa73f1e42e8515edf9deef2/Dockerfile#L13).

The environment variable will be ported to the docker-compose service, which means that this port will be used to start the express server. In any case, either the Dockerfile statement or [this config key](https://github.com/Wingysam/Christmas-Community/blob/fe6bf0f474f3fbbd8aa73f1e42e8515edf9deef2/config/index.js#L6) should be modified to be equivalent to each other.

**Comment by Wingysam** [comment]
I see! If the forward for 3000 doesn't do anything, can you remove that? Thanks!

**Comment by coalio** [comment]
I assumed you're more comfortable starting and previewing the application at port 3000, so I've modified the Dockerfile to start the Express server at 3000.

Additionally I noticed that the DB does not have a default port specified in the initial config so I've included that too so it matches the Dockerfile.

**Comment by Wingysam** [comment]
I think it's better to keep it at 80 for backward-compatibility with existing deployments. The database should not be exposed by default because it doesn't have any security aside from not be accessible by network. Could you change it to listen on 80 and only forward 80? Thanks!

**Comment by coalio** [comment]
Sure, I'll do the changes after work

**Comment by coalio** [comment]
@Wingysam done!

**Review by Wingysam — CHANGES_REQUESTED** [review]
It looks like config/index.js was accidentally run through a formatter and no longer looks like the rest of the project, could you fix that please? Thanks!

**Comment by coalio** [comment]
Done!

**Review by Wingysam — APPROVED** [review]

**Comment by Wingysam** [comment]
Thank you!

**Pull request merged**
