### PR TITLE
fix: solve ???/??? for logged in user's wishlist

### LINKED ISSUE #88: Discussion: logged in user sees ???/??? on wishlists overview
When you are logged in to some account, it shows `???/???` statically rendered through the `WISHLISTS_COUNTS_SELF` variable in a language js file. In below image, I am logged in as `dan`.
image

Would it make more sense to replace `???/???` with `?/X`, where `X` is the total of my own list? This is information that I know. What are your thoughts?

### PR DESCRIPTION
**Pull request by cj13579**
This proposed change looks to resolve the '???/???' stuff that's seen by the logged in user. There's also a "bonus" change of setting the VS Code default node port to make things more consistent with if you start the application using `npm start`.

This change removes a block of code that treated the logged in user differently from other users. I don't think that this is necessary. With this change, all lists are processed with the same logic. I've added some tidy-up to the language files too as the `WISHLISTS_COUNTS_SELF` string is no longer required.

If accepted this issue closes #88.

### CODE REVIEW

**Comment by cj13579** [comment]
That's fair. It shows the total of the list. I still think that's better than _???/???_ but I can have a think about filtering this list too.

**Comment by Wingysam** [comment]
I think it's best to calculate how many items you've added to your own list in the JS route handler and pass that as a property to the pug template rather than calculating it in pug.

**Comment by cj13579** [comment]
> I think it's best to calculate how many items you've added to your own list in the JS route handler and pass that as a property to the pug template rather than calculating it in pug.

Yep, that makes sense. With this commit (https://github.com/Wingysam/Christmas-Community/pull/105/commits/152a562e8308baebceae33237b362f10fb2632ec) I've updated the `totals()` function to calculate self added items. I've modified the view to call that function for each wish list once and then use the metrics needed as appropriate. For deployments with large numbers of lists, a performance improvement should be seen since the calculations for pledge counts etc. is only done once where it was done many times before.

**Comment by cj13579** [comment]
I feel like the files change on this branch are all weird and I'm worried that we might be introducing some regressions. How do you feel about closing this and I'll open a new one cherry-picking the relevant commits.

**Pull request closed without merging**
