### PR TITLE
Add fr-fr translation

### PR DESCRIPTION
**Pull request by Na0mir**
Few wording update + add one missing key

### CODE REVIEW

**Comment by Wingysam** [comment]
Thank you!

**Comment by hilsonp** [comment]
Could you please update the docker image ?

**Comment by Wingysam** [comment]
I haven't tagged a release since this was merged. I'll do that now.

**Comment by Wingysam** [comment]
1.30.2 is now on Docker Hub.

**Comment by hilsonp** [comment]
Thank you !

**Pull request merged**
