### PR TITLE
feat. beta level group functionality

### PR DESCRIPTION
**Pull request by jskiddie**
I needed usergroups, so I added them.
Please excuse my most likely bad coding style as this is my first time using Javascript. I have marked this as beta functionality as I am unsure wether or not it works perfetcly and is truly ready for production. I would love for others to try this out to determine if it works correctly I am very open to feedback. This implementation if far from Saas ready or anything close to that.

### Added beta group functionality:

- is it the best implementation possible ? _NO_
- is it the fasttest ? _NO_ adding to and removing from groups is crazy expensiv
- is it the one with the smallest storage space footprint ? _NO_ data is saved three times redundant just a nightmare of data integrety
- does it work ? **YES**
	- Or at last I was unable fo find any major bugs

#### How to enable
- Make and be shure it works
- ADD an ENV GROUPING and set it to true
- For existing setup continue on this sidequest
	- it is reccomended nobody access the install in this state
	- Go to Settings and click the "migrate to groups button"
- Done

#### Setup
- By default grouping is disabled for everyone
- create a new group under settings
	- type in a group name
	- click "add group"
- add a user to the group by clicking "edit" on the corrosponding group
	- type in the correct name of the user under "username"
	- click "Add users to group"
- once a user is added to a group grouping is disabled for them, they can only see lists of people in his group,
  his lists can be seen by everyone he shares a group with as well as users for whom grouping is disabled

## Misc
I stopped to do code cleanup, since it always broke it trying.

### CODE REVIEW

**Comment by Wingysam** [comment]
That's an impressive way to hack it in! I think this implementation makes maintaining the project difficult but I'd be happy for it to be a fork like Christmas-Community-with-Groups until I implement it how I want it.

**Comment by Wingysam** [comment]
I've closed this as it won't be merged into the main project. I'll add a link to your fork in the README until the main project has the feature.

**Comment by jskiddie** [comment]
I have done my best to seperate the fork thanks for mentioning it in the README. 
Do you think we will be able to migrate the data from the Fork to the normal version once you are finished ?

**Comment by Wingysam** [comment]
I don't think so, unless you can write some code to migrate your database schema to the new SQL schema. Maybe a migration script that iterates through all of the data and populates the database with it rather than an automatic migration?

**Comment by jskiddie** [comment]
Sounds like a possible solution, especially because I suppose I will have a migration script you'll create to migrate useers to start off from.

**Pull request closed without merging**
