### PR TITLE
Add Romanian localization

### PR DESCRIPTION
**Pull request by BootVirtual**
I finished almost all strings except for the ones containing the word "pledge". I don't really understand what it means in these cases. Ping me if you need anything!

Edit: I forgot to add, this pull request is for Hacktoberfest

### CODE REVIEW

**Comment by Wingysam** [comment]
Pledge means that you intend to purchase the item and give it to the person. It means that other people won't give the same gift because they know you are giving that gift already. Does that make sense? @BootVirtual

**Comment by BootVirtual** [comment]
Alright, I'll add another commit later today or sometime this week.

**Comment by BootVirtual** [comment]
I finally managed to get the whole thing translated. Thanks for your help!

**Comment by Wingysam** [comment]
Thank you!

**Pull request merged**
