### PR TITLE
Create Helm Chart

### PR DESCRIPTION
**Pull request by ndlanier**
Implements #10

- Creates a pod using wingysam/christmas-community
  - Current Image tag is set to 1.30.0
- Creates a pvc and pv to store the /data directory housing the db to retain data if pod recreates
- Creates kube service account by default
- Not by default, can create the following
  - Ingress resource

Note: I removed the default helm template horizontal auto-scaler as I find it highly unlikely anyone is going to scale this to a massive point of needing more than one pod. The DB being baked into the docker image will prevent horizontal scaling anyways.

### CODE REVIEW

**Comment by ndlanier** [comment]
I'll create a repo to house the packaged versions of the helm chart

**Comment by ndlanier** [comment]
Chart Release Repository: https://github.com/ndlanier/christmas-community-chart-release
Helm repo url: https://ndlanier.github.io/christmas-community-chart-release/

Example deployment resource map:
image

It's up and running for me locally:
image

**Comment by ndlanier** [comment]
Need to add values for env variables before this is approved or merged

**Comment by Wingysam** [comment]
Thank you for making this! I'm concerned that the chart won't be updated when new versions of Christmas Community are released. Is it possible to somehow automate updating the chart with GH Actions? Ideally it would be in this repository to avoid trusting a community-managed project.

**Comment by ndlanier** [comment]
No problem!
For patches and fixes, the only thing that will need updated is the default image tag which can be overridden so that won't be a big deal. We might be able to set up an action to do an automated commit that would sed the default image tag.

For any new features or big releases (new env variable, or migrating the db to use sql as examples) that will likely require manual intervention to account for the changes.

**Comment by ndlanier** [comment]
But when there is a new release of the chart we can automate the deployment to the helm repo via gh actions for sure.

**Comment by ndlanier** [comment]
> Ideally it would be in this repository to avoid trusting a community-managed project.

If you want to host the helm repo using this github repo you'll need to follow this guide: https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417

If you go that route you'll either be dropping a lot of tarballs in the root of the repo or you'll be using the docs directory.

**I have update the chart to contain the environment variables**

**Comment by ndlanier** [comment]
Ok now it should be ready, I've tested locally and everything is working. 

I have commented out the env variables on the default values file so the container defaults are not overridden.

**Comment by ndlanier** [comment]
Any other questions or concerns?

**Comment by Wingysam** [comment]
Okay that sounds ideal, thank you!

**Pull request merged**
